use_frameworks!
platform :ios,'12.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

target "NewHangGuanTong" do
  pod 'AFNetworking', '~> 4.0.1'
  pod 'YYModel', '~> 1.0.4'
  pod 'Masonry', '~> 1.1.0'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'MJRefresh', '~> 3.7.2'
  pod 'IQKeyboardManager', '~> 5.0.6'
  pod 'FMDB', '~> 2.7.5'
  pod 'SDWebImage', '~> 5.12.1'
  pod 'SDCycleScrollView', '~> 1.82'
  pod 'BaiduMapKit' #百度地图SDK
  pod 'BMKLocationKit' #百度地图定位SDK
  pod 'TZImagePickerController', '~> 3.6.7'
  pod 'JPush'
  pod 'PGDatePicker', '~> 2.6.9'
  pod 'JXCategoryView', '~> 1.5.9'
  pod 'ReactiveObjC', '~> 3.1.1'
end
      
